module.exports = [
    {
        firstName: "Michelle",
        lastName: "Obama",
        living: true,
        bountyAmount: 500,
        type: "Jedi",
    }, {
        firstName: "Ilana",
        lastName: "Glazer",
        living: true,
        bountyAmount: 300,
        type: "Sith",
    }, {
        firstName: "Jessica",
        lastName: "Jones",
        living: true,
        bountyAmount: 1000,
        type: "Sith",
    }, {
        firstName: "Veronica",
        lastName: "Mars",
        living: true,
        bountyAmount: "500",
        type: "Jedi",
    }, {
        firstName: "Oprah",
        lastName: "Winfrey",
        living: true,
        bountyAmount: 400,
        type: "Jedi",
    }, {
        firstName: "Amy",
        lastName: "Winehouse",
        living: false,
        bountyAmount: 100,
        type: "Sith",
    }, {
        firstName: "Abbi",
        lastName: "Jacobsen",
        living: true,
        bountyAmount: 300,
        type: "Jedi",
    }, {
        firstName: "Rosa",
        lastName: "Parks",
        living: false,
        bountyAmount: 600,
        type: "Jedi",
    }, {
        firstName: "Cat",
        lastName: "Woman",
        living: true,
        bountyAmount: "700",
        type: "Sith",
    }, {
        firstName: "Oliva",
        lastName: "Moore",
        living: false,
        bountyAmount: "500",
        type: "Jedi",
    }
]